[book]
authors = ["ISIA Lab"]
language = "en"
multilingual = false
src = "src"
title = "ISGT Wiki"

[output.html]
smart-punctuation = true
git-repository-url = "https://github.com/numediart/ISGT"
git-repository-icon = "fa-github"